language: go
script:
- mkdir -p build
- go build -o build/textmail
deploy:
  provider: releases
  api_key:
    secure: YqtoH6UAOohELxpgcXEwqPHubZV6fFqKVnAU5fSXq4AVuUAazYIjAR9uVIZk4a2rxGCqsVlySBTH4+GUX+BSFGLI2gTw/RXXDayG2or2fpdHionipn0zSgD5YK32A5jw/ORmdoLtd/45c9TGcxL5Jptc+fPYbhQxZfs+q9alhmQUWnLnMew/OvsZ4GXFKV+Q52lobq28lzl8eRLFiwvrTd34cAEPm4nzJnGNxTHqOtaI4MOjMps8LMVKNgqCidbmaP1Vwmw1DsZ91GgFH7DiKUhpT5/lpDoLAnJLefIh8rubsqV5yLhhWJjHVEYf0EVqSjScFwXC6+iP4SzsujRJwPGrl27mKIpu6svU74gG1AkX3Kgwx+UhqZzb9FbIoX6faG6VSldTMQXKQMtc39ATrWmENX+SrfE86gvK0WKE7XyimhwakM/77pU36iI8A0k0mk2KbAMlDnOlb9sjow78KnpZXkQOVwyq9S9k0sb5A5YjW8vr08zKUx22ePcrjJiPmWvvxoBAKlg9aUz5/UURyCAsrZ8rDmtwGnC+aFI4ilED9enf+RJfKd6l6+NtUce0eFrxtnyZBVA/LYem0z+cgrKFtKaVSD5RdnAZPInz4yaXHlHUovfDW9JUkfsCO6GP0e5jmeCX94BBUzrHVor/u0mAp55uSJh4LzlQ2VPWUC4=
  file: build/textmail
  on:
    repo: cfstras/textmail
    tags: true
